[package]
name = "app"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"


[profile.release]
opt-level = 3
lto = "fat"
debug = "none"
panic = "abort"
codegen-units = 1